services:
  - type: web
    name: drcare-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /
    envVars:
      - key: ALLOWED_ORIGINS
        value: "*"
